### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by madagon**
Added expiration time to the options

### CODE REVIEW

**Comment by eddturtle** [comment]
Everything ok with this?

**Comment by madagon** [comment]
yes but i can't push. Do i need to a permission?

**Comment by eddturtle** [comment]
You're trying to merge the develop branch into master? I can see your fork but there aren't any changes in it.

**Comment by madagon** [comment]
no i just wanna push my changes into the develop branch. sorry it's the first i'm trying to do this on github. what should i do? i have the committed changes on local. when i try git push i get permission error.

**Comment by madagon** [comment]
anyway here's the new file, you may apply yourself

## Signature.php

```
    protected $options = [

        // If the upload is a success, the http code we get back.
        'success_status' => '201',

        // If the file should be private/public-read/public-write.
        // This is file specific, not bucket. More info: http://amzn.to/1SSOgwO
        'acl' => 'private',

        // The file's name, can be set with JS by changing the input[name="key"]
        // ${filename} will just mean the filename of the file being uploaded.
        'default_filename' => '${filename}',

        // The maximum file size of an upload in MB.
        'max_file_size' => '500',

        // Request expiration time, specified in relative time format or in seconds.
        // min: 1 ("+1 second"), max: 604800 ("+7 days")
        'expiration' => '+6 hours'

    ];
```

...

```
private function getExpirationDate()
{
    $exp = strtotime($this->options['expiration'], $this->time);
    $diff = $exp - $this->time;

    if (!($diff >= 1 && $diff <= 604800))
        $exp = '+6 hours'; //use default interval when expiration was out of range

    return gmdate('Y-m-d\TG:i:s\Z', $exp);
}
```

**Comment by eddturtle** [comment]
Haha! Ohh well, thank you v. much (I'll get that pushed this evening)

(great addition by the way)

**Comment by madagon** [comment]
your welcome!
i'll learn how to use github soon. lol

**Comment by madagon** [comment]
and thanks for this library. saved my time.

**Comment by madagon** [comment]
i've got another patch

```
protected $options = [

        // If the upload is a success, the http code we get back.
        'success_status' => '201',

        // If the file should be private/public-read/public-write.
        // This is file specific, not bucket. More info: http://amzn.to/1SSOgwO
        'acl' => 'private',

        // The file's name, can be set with JS by changing the input[name="key"]
        // ${filename} will just mean the filename of the file being uploaded.
        'default_filename' => '${filename}',

        // Validation prefix for the filename.
        // Server must check the filename to be started with this prefix.
        'valid_prefix' => '',

        // The maximum file size of an upload, specified in MB.
        'max_file_size' => '500',

        // Request expiration time, specified in relative time format or in seconds.
        // min: 1 ("+1 second"), max: 604800 ("+7 days")
        'expiration' => '+6 hours'

    ];
```

...

```
protected function generatePolicy()
    {
        $maxSize = $this->mbToBytes($this->options['max_file_size']);
        $policy = [
            'expiration' => $this->getExpirationDate(),
            'conditions' => [
                ['bucket' => $this->bucket],
                ['acl' => $this->options['acl']->getName()],
                ['starts-with', '$key', $this->options['valid_prefix']],
                ['starts-with', '$Content-Type', ''],
                ['content-length-range', 0, $maxSize],
                ['success_action_status' => $this->options['success_status']],
                ['x-amz-credential' => $this->credentials],
                ['x-amz-algorithm' => self::ALGORITHM],
                ['x-amz-date' => $this->getFullDateFormat()]
            ]
        ];
        $this->base64Policy = base64_encode(json_encode($policy));
    }
```

**Pull request closed without merging**
