### PR TITLE
Add support S3-compatible storage solutions

### PR DESCRIPTION
**Pull request by ZAZmaster**
Add support S3-compatible storage solutions

### CODE REVIEW

**Comment by eddturtle** [comment]
Hi ZAZmaster, thanks for the pull request - I'm hesitant to merge this because it changes the signature __construct, meaning for anyone who is already using this package it won't work, or won't work as expected for them. Saying this however, I'm sure we'd be able to accommodate this functionality, so I'll put something together and get back to you.

**Comment by ZAZmaster** [comment]
@eddturtle you can move my first param to end of __construct signature.
```
public function __construct($key, $secret, $bucket, $region = "us-east-1", $options = [], $server = "amazon")
```
This not brake already exist config, but in new config allow to use own s3

**Comment by ZAZmaster** [comment]
@eddturtle you can also tie it at $options it would be more correct!

**Comment by eddturtle** [comment]
Hi again, just released a new version (1.6.2) which supports custom urls being passed into options.

**Pull request closed without merging**
